#!/usr/bin/env python3
"""
Generate a Presidio custom PatternRecognizer from a list of custom regex patterns.

Output is a Python file (e.g. /app/presidio_analyzer/conf/custom_recognizer.py)
that can be imported and added to the AnalyzerEngine registry.

Each pattern becomes a Presidio `PatternRecognizer` with:
  - name: the user-provided name (e.g. "TV_MODEL")
  - pattern: the user-provided regex
  - supported_language: optionally constrained to a specific language
  - score: configurable per-pattern, defaults to 0.5

Usage:
    python generate_custom_recognizer.py \\
        --patterns '[{"name": "TV_MODEL", "regex": "(\\\\d{2,3})qned\\\\w+", "score": 0.7}]' \\
        --output /app/presidio_analyzer/conf/custom_recognizer.py
"""

import argparse
import ast
import sys
from pathlib import Path
from typing import Any


# Default score for custom patterns (Presidio requires a value, 0.0-1.0)
DEFAULT_SCORE = 0.5


def validate_pattern(p: dict[str, Any]) -> tuple[str, str, float, str | None]:
    """Validate a single pattern entry. Returns (name, regex, score, language)."""
    if "name" not in p or not p["name"]:
        raise ValueError("Pattern missing 'name'")
    if "regex" not in p or not p["regex"]:
        raise ValueError(f"Pattern '{p['name']}' missing 'regex'")

    name = str(p["name"])
    regex = str(p["regex"])
    score = float(p.get("score", DEFAULT_SCORE))
    if not 0.0 <= score <= 1.0:
        raise ValueError(f"Pattern '{name}' score must be 0.0-1.0, got {score}")

    # Optional: constrain to a specific language (otherwise applies to all)
    language = p.get("language")
    if language:
        language = str(language)

    return name, regex, score, language


# Note: Presidio's PatternRecognizer requires the regex to compile
# without the 'g' flag. We strip it if present and use re.compile().
# Anchors (^ and $) in user patterns are kept as-is; Presidio's
# PatternRecognizer applies them per match.
GENERATED_FILE_HEADER = '''"""Auto-generated Presidio custom recognizers.
DO NOT EDIT — this file is regenerated by generate-custom-recognizer.py
during the Docker build from PasteGuard's secrets_detection.custom_patterns
config field.

Each pattern is a Presidio PatternRecognizer that runs inside the
AnalyzerEngine, benefiting from NLP context, scoring, and conflict
resolution with the built-in recognizers.
"""

from presidio_analyzer import PatternRecognizer, Pattern
'''


def render_pattern(name: str, regex: str, score: float, language: str | None, deny_list: list[str] | None = None) -> str:
    """Render a single pattern recognizer as Python source.

    Uses ast.literal_eval to safely embed the regex string (handles backslashes).
    The regex is compiled with re.IGNORECASE for forgiving matching.
    """
    # Use ast.literal_eval to safely embed the regex source (preserves escapes)
    try:
        # ast.literal_eval will produce a Python string with proper escaping
        safe_regex_repr = ast.literal_eval(f'"{regex}"')
    except (ValueError, SyntaxError):
        # Fallback: use repr
        safe_regex_repr = repr(regex)

    deny_list_str = ""
    if deny_list:
        deny_list_items = ",\n        ".join(ast.literal_eval(f'"{x}"') for x in deny_list)
        deny_list_str = f",\n    deny_list=[\n        {deny_list_items}\n    ]"

    language_str = ""
    if language:
        language_str = f",\n    supported_language={ast.literal_eval(f'\"{language}\"')}"

    return f'''
# Pattern: {name} (score={score}, language={language or "*"})
_custom_recognizer_{name} = PatternRecognizer(
    name={ast.literal_eval(f'"{name}"')},
    patterns=[Pattern(name={ast.literal_eval(f'"{name}_pattern"')}, regex=r"{regex}", score={score})]{language_str}{deny_list_str},
)
'''


def render_register_block(names: list[str]) -> str:
    """Render the registration function that returns all custom recognizers."""
    instances = ",\n    ".join(f"_custom_recognizer_{name}" for name in names)
    return f'''

def get_custom_recognizers():
    """Return a list of all auto-generated custom recognizers.
    Called by app.py / app_secondary.py to register them with the AnalyzerEngine.
    """
    return [
        {instances}
    ]
'''


def generate(patterns: list[dict[str, Any]], output: Path) -> None:
    """Generate a Python file containing Presidio custom recognizers."""
    if not patterns:
        # Write a no-op file
        output.parent.mkdir(parents=True, exist_ok=True)
        with open(output, "w") as f:
            f.write(GENERATED_FILE_HEADER)
            f.write("\n# No custom patterns configured.\n\n")
            f.write("def get_custom_recognizers():\n    return []\n")
        return

    validated = [validate_pattern(p) for p in patterns]

    # Sort by name for deterministic output
    validated.sort(key=lambda t: t[0])

    body_parts = [GENERATED_FILE_HEADER]
    for name, regex, score, language in validated:
        body_parts.append(render_pattern(name, regex, score, language))
    body_parts.append(render_register_block([n for n, *_ in validated]))

    output.parent.mkdir(parents=True, exist_ok=True)
    with open(output, "w") as f:
        f.write("".join(body_parts))

    print(f"  - {output} ({len(validated)} custom recognizer(s))")


def main():
    parser = argparse.ArgumentParser(description="Generate Presidio custom recognizers")
    parser.add_argument(
        "--patterns",
        required=True,
        help='JSON array of patterns, e.g. \'[{"name": "X", "regex": "..."}]\'',
    )
    parser.add_argument(
        "--output",
        default="/app/presidio_analyzer/conf/custom_recognizer.py",
        help="Output Python file path",
    )
    args = parser.parse_args()

    try:
        patterns = ast.literal_eval(args.patterns)
    except (ValueError, SyntaxError) as e:
        print(f"Error: failed to parse --patterns JSON: {e}", file=sys.stderr)
        sys.exit(1)

    if not isinstance(patterns, list):
        print("Error: --patterns must be a JSON array", file=sys.stderr)
        sys.exit(1)

    generate(patterns, Path(args.output))
    print("Done!")


if __name__ == "__main__":
    main()
